# https://taskfile.dev
version: '3'

tasks:
  default:
    deps: [run, open]
  
  run:
    desc: run serve
    cmds:
      # Start the built-in live server including draft
      - hugo server --buildDrafts

  open:
    desc: open web server
    cmds:
      - open http://localhost:1313/

  dep:
    desc: build to /public
    cmds:
      - hugo -D
      # Output will be in ./public/ directory by default
      # (-d/--destination flag to change it, or set publishdir in the config file).



  try-new:
    desc: try as https://gohugo.io/getting-started/quick-start/
    cmds:
      - hugo new site quickstart
      #  $ hugo new site quickstart
      #  Congratulations! Your new Hugo site is created in /Users/cao/dev/hello-hugo/quickstart.
      #
      #  Just a few more steps and you're ready to go:
      #
      #  1. Download a theme into the same-named folder.
      #  Choose a theme from https://themes.gohugo.io/ or
      #  create your own with the "hugo new theme <THEMENAME>" command.
      #  2. Perhaps you want to add some content. You can add single files
      #  with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
      #  3. Start the built-in live server via "hugo server".
      #
      #  Visit https://gohugo.io/ for quickstart guide and full documentation.

      - |
        cd quickstart
        git init
        git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
        echo theme = \"ananke\" >> config.toml
        hugo new posts/my-first-post.md

  try:
    cmds:
      - cd quickstart && hugo server -D

  version:
    desc: show hugo version
    deps: [install-hugo]
    cmds:
      - hugo version

  install-hugo:
    desc: install hugo
    status:
      - which hugo
    cmds:
      - brew install hugo